### PR TITLE
Don't use a dynamic version for com.amazonaws:aws-java-sdk-s3.

### LINKED ISSUE #20: Don't use a dynamic version for com.amazonaws:aws-java-sdk-s3
Dynamic versions published in the pom cause unnecessary trips to maven repo to check if new version is available for consumers and can lead to non-reproducible builds

### PR DESCRIPTION
**Pull request by erdi**
Fixes #20.

### CODE REVIEW

**Comment by myniva** [comment]
Pinning the version of the S3 SDK has revealed some vulnerabilities in the dependency tree (see Snyk report).

According to https://github.com/aws/aws-sdk-java/blob/master/pom.xml the AWS SDK only stays on Jackson 2.6 for Java 6 backwards compatibility.

I suggest, we try to pin Jackson to something >=  2.8.11

**Comment by myniva** [comment]
As an alternative, we could also try to upgrade to the AWS SDK 2.0 (which is using Jackson 2.9). Not sure how much the API changed though...

**Comment by erdi** [comment]
To be honest with you, I won't have capacity to tackle either of the options listed by you in the upcoming month (as I'm preparing for Gr8Conf). The test coverage is fairly thin and I'd be very nervous making such significant changes to the library without being able to automatically verify them. 

I think it's best to leave it as is for the time given I have a workaround in place already for what made me submit this PR. Somewhe down the line I'd add some integration tests using something like https://github.com/adobe/S3Mock and when that gets merged try tackling one of the suggested options. How does that sound?

**Comment by myniva** [comment]
Hi @erdi I am doing some cleanup and close this PR for now. Please don't mind to open a new one as soon as you got the capacity to work on this issue.

**Pull request closed without merging**
