### PR TITLE
Replace byte[] with File and pin AWS SDK version

### PR DESCRIPTION
**Pull request by nhoughto**
as per #26  and #20

### CODE REVIEW

**Comment by myniva** [comment]
Hi @nhoughto ,

thanks for opening this pull request. I have a couple of comments and thoughts:

First of all, I don't feel comfortable changing the implementation without having a proper integration test. The current unit tests are more or less specific to the actual implementation. Before moving on with this, we need integration tests for at least `AwsS3BuildCacheService#store` and `AwsS3BuildCacheService#load`.
Running the tests against a mocked version of S3 seems to be a viable solution. We could look into https://github.com/adobe/S3Mock

Beside that, I am not sure whether we should write & read the cache object to disk in all cases for performance considerations (IO is usually quite expensive). So far, doing all of that in memory hasn't been a problem and seems to be related to very large cache objects only. If I am not mistaken, Gradle already uses the Guava lib. So we could try to use https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/io/FileBackedOutputStream.html instead.

**Comment by nhoughto** [comment]
Yeah checking size before going to disk is a good idea, only write out to a file if the length is greater than N bytes. What would N be in this situation? 1MiB?

**Comment by myniva** [comment]
By default, the Gradle daemon seems to be running with 512MB heap (see https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory). It is hard to come up with a good number, but I'd say it should usually be fine to load up to 50MB into memory. Some Gradle tasks are executed in parallel tough and hence the limit should be smaller. What about 5MB? Seems to be large enough for a lot of use cases and gives enough room for parallel execution.

**Comment by nhoughto** [comment]
Actually I just went to do this, we don't know the length of the cache item until after its written to the OutputStream, which is too late to decide whether to hit disk or not.. as the OutputStream needs to be backed by something.

So if it can't be dynamic based on size, the only option is to make it globally configurable in the plugin, so it can be toggled on / off depending on the usecase?

**Comment by vlsi** [comment]
> we don't know the length of the cache item until after its written to the OutputStream

@nhoughto , AFAIK BuildCacheEntryWriter has `getSize()` method: https://docs.gradle.org/current/javadoc/org/gradle/caching/BuildCacheEntryWriter.html

Does it work?

**Pull request closed without merging**
